export type CoffeeType = {
  _id: string;
  name: string;
  brand: string;
  type: string;
  origin: string;
  roastLevel: string;
  processing: string;
  qGrading: string;
  altitude: number;
  flavorNotes: string[];
  aroma: string;
  acidity: number;
  body: number;
  sweetness: number;
  price: number;
  ratingsAverage: number;
  ratingsQuantity: number;
  summary: string;
  image: string;
  locations: {
    type: string;
    coordinates: number[];
    description: string;
    _id: string;
    id: string;
  }[];
  slug: string;
  id: string;
};
